### ISSUE TITLE
ツールとか

### ISSUE THREAD

**Issue by yuuki** [motemen/isucon-qualifier-2014#1]
# モニタリング系
- dstat
- tcpdump
- strace
- perf
- innotop
- pidstat
- mackerel-agent 
# CPAN
- Starlet
- Plack::Middleware::Axslog (LTSV)
- Plack::Middleware::ServerStatus::Lite
- Devel::KYTProf
- Devel::NYTProf
- MySQL::Warmer
# デプロイ
- Capistrano

**Comment by yuuki** [comment]
きっと僕が知らない奴がいろいろある？

**Comment by yuuki** [comment]
計測期間1分だから mackerel-agent いらなさそう...

**Comment by motemen** [comment]
せっかくだし入れてみようぞ < mackerel-agent

**Comment by yuuki** [comment]
適当に org 作っときます "Isucon" あいてた

**Comment by yuuki** [comment]
招待しました!!

**Comment by Songmu** [comment]
一台構成だからdeployは普通にシェルとかで良いと思われる。cap使ってもいいけど。git pullしてsupervisord再起動とかだけで良さそう。

**Comment by Songmu** [comment]
最初にベンチ回す。ベンチ回す際には、
- topとかdstatとかで見守ってボトルネック探す
- ベンツマークツールのアクセス傾向を探る
  - どのパスにどれくらいアクセスが来るか
  - パスごとの平均レスポンスタイムはどれくらいか

みたいなところができるようになって良さそう。

**Comment by Songmu** [comment]
なんか、アクセス傾向探るの、fujiwaraさんはワンライナー芸で色々やってたけど、そういうスキル無いからツール作っておけばよかったな～とか今更思ってる。

**Comment by yuuki** [comment]
motemen さんが cap 得意なので、パッと実装いただけそう&いつもと同じという理由だけでした。シェルでもいいと思います。

supervisordで Perl アプリケーション動かしたことないですが（Graphite系は動かしてる）、パフォーマンス影響はないので、やりやすいものでおまかせしたいと思います。(社内は全部 daemontools )

**Comment by yuuki** [comment]
ベンチ同じ考えでした。

LTSV形式のログならパースできるやつ前に問題解いたときに雑なやつ書いてました。
https://gist.github.com/y-uuki/129983ab4b02e3a646ad
キー名とか決め打ち、標準外モジュール使ってて、ださい。

> どのパスにどれくらいアクセスが来るか
> パスごとの平均レスポンスタイムはどれくらいか

多分これできたはず。

**Comment by Songmu** [comment]
僕もdaemontoolsスキーなんだけど、過去の傾向からすると、supervisordでdaemonizeされてる可能性が高い。別にそこをわざわざ置き換える必要はないだろうなというところ。

**Comment by yuuki** [comment]
最初からそうなってるならそれでよさそうですね
