### ISSUE TITLE
方針とか

### ISSUE THREAD

**Issue by yuuki** [motemen/isucon-qualifier-2014#2]
好き勝手にチューニングとか手を付ける前に全員である程度ボトルネックっぽいところを洗い出して手順を決めてチューニングとか。

過去のブログみるとだいたい事前にちゃんと方針決めたほうがよかったみたいなことが書いてある。
あと、だいたい正攻法(競技でなくても通用する)でチューニングした人が勝ってるイメージがある。

知見ください。

**Comment by yuuki** [comment]
http://motemen.hatenablog.com/entry/2013/10/07/ISUCON3_%E4%BA%88%E9%81%B8_2_%E6%97%A5%E7%9B%AE%E3%81%AB%E5%8F%82%E5%8A%A0%E3%81%97%E3%81%9F%EF%BC%88%E6%9A%AB%E5%AE%9A_5_%E4%BD%8D%EF%BC%89_%23isucon

```
誰でもデプロイできるようにしておかないと、互いの時間が有効に使えない
誰でもベンチマーク取れるようにしておかないと同上。インスタンスもうひとつ作ってもよかったなと思った
そもそも最初どんな風にコードを管理するか、とか、デプロイするか、というのを決めてなかったのがよくなかった
データの更新が遅れてもよいというレギュレーションをうまく活用できなかった
Yappo さんの記事が参考になった。こういうところ自信もってキッチリ実装できる必要があるなと思った。
```

なるほど〜〜

**Comment by yuuki** [comment]
http://wtatsuru.hatenadiary.com/entry/2013/10/06/233617

```
こっからは読まなくていいです
予習足りなかった：前日やればいいやと思ってたけど 酔いつぶれて一日中寝てた とかそういうの。ひどかった。
知らないミドルウェア大杉：varnish はだましだまし、MySQL5.6 そんなに触ってないからけっこうその場で調べたり。
発想の転換：当たり前の発想しかなかった。優勝クラスの人たちに結局ダブルスコア以上つけられてしまったのは、二人にまかせて思考停止してた部分があったなーと。
武器をそろえる：普段からワンライナー書いてばかりだからその場で sed awk 書きまくってたけど、ちゃんとツールにするべきだなーと思った。自分の中でのパフォーマンス解析の定番的な。
デプロイとか考えてなかった。そこが直列になってしまった。
```

なるほど〜〜

**Comment by Songmu** [comment]
予選は基本無理する必要ないので正攻法で良いと思われる。使い慣れてる構成にさっさとしてしまうのが良いと思う。proxyとか最初apacheになってる可能性高いから、さっさとnginxにして、静的ファイルのサーブはnginxでさばくとか、ログ形式は使い慣れてるやつにするとか、そのへんは決め打ちでやってしまって良さそう。

**Comment by yuuki** [comment]
なるほど〜〜
nginx & LTSV が好きです

**Comment by yuuki** [comment]
## 決め打ち？
- Nginx
  - LTSV
  - 静的ファイル返す
  - ワーカー数はとりあえずコア数くらい
- Starlet
  - ワーカー数は最初はとりあえずコア数 x2 ぐらいで
- MySQL 5.6 (多分デフォルト？)
  - buffer poll size 増やすぐらい メモリの80%
- もし必要であれば
  - memcached
  - Redis
    - AOFとか切るぐらい？

varnish とか使えないので、動的生成ページのキャッシュは難しいかも...。
nginx でキャッシュさせられなくもない。
キャッシュは麻薬だから更新ないとわかってるものぐらいで。

**Comment by Songmu** [comment]
Starletとかは、--max-reqs-per-childとかを50000とかにしておくという小技があります。

**Comment by yuuki** [comment]
あ、それみました！どうせ3分だしプロセス破棄する意味なさそう。

**Comment by yuuki** [comment]
ミドルウェアチューニングは最小限で、Devel::NYTProf でアプリの遅いところ治していくのが一番効きそうという印象

**Comment by Songmu** [comment]
とりあえず最初にソース一式をgitにpushしてもらいたいかなー。perlのとこだけで良さそう。で、いろいろ整えてもらっている間に、motemenと僕でソース読む。

**Comment by yuuki** [comment]
あ、はいそうですね。
読んでもらってる間気になる所、issue にコメントしていってもらえるとうれしいです。

**Comment by Songmu** [comment]
アプリネックになってNYTProfが必要なところまで持っていくの結構大変。

**Comment by Songmu** [comment]
あと、mysqlはslowlogちゃんと出るようにしておくの大事。

**Comment by motemen** [comment]
`X-Dispatch` みたいなレスポンスヘッダを吐いてアクセス傾向みるってのを前回やってた

**Comment by yuuki** [comment]
確かに、ミドルウェアを普通のレベルにはチューニングできないと、アプリネックにはならなさそう。変な罠とか心配。

slowlog 絶対出します。

`X-Dispatch` 便利そう。はてなっぽい。

**Comment by yuuki** [comment]
とりあえずここに書いてありそうなことはやるぞ!! http://www.slideshare.net/kazeburo/isucon-summerclass2014action2final

**Comment by Songmu** [comment]
やるぞ！実際問題としては、そこに書いてあること全部やるの時間的に厳しいので、優先度を決めて「効きそうなやつ」から片付けていくのが大事だと思われる。

**Comment by yuuki** [comment]
"優先度を決めて「効きそうなやつ」から片付けていく" 了解です。
