### ISSUE TITLE
ソースコード気になる所

### ISSUE THREAD

**Issue by yuuki** [motemen/isucon-qualifier-2014#4]
最初にアプリのコード読んで気になるところ列挙

**Comment by Songmu** [comment]
今どきPerlなの気になる…

**Comment by yuuki** [comment]
気になりそう

**Comment by Songmu** [comment]
- サブクエリ使いまくってるので最適化できそう
- `login_log WHERE ip =...`とかしてるけど、IPにindex無い

**Comment by motemen** [comment]
ログイン失敗数とかをオンデマンドで引いてあるあたりなんとかなりそう

**Comment by motemen** [comment]
テンプレートは変なとこなさそう。とりあえずテーブル設計まともにしたら次の問題が出てくるってかんじかな

**Comment by motemen** [comment]
https://github.com/motemen/isucon-qualifier-2014/blob/b71b2da/lib/Isu4Qualifier/Web.pm#L47-49

最後のログイン成功以降の失敗数が閾値 **以上** だとロックされる

**Comment by Songmu** [comment]
attempt_loginが重い
- ユーザー一行引いてくる
- ip bann判定 `ip_banned`
- ユーザーロック判定 `user_locked`
- パスワード検証

という順番になってる
